#!/usr/bin/env bash
# Generate QCOW2 corpus images using qemu-img.
# Requires: qemu-utils (sudo apt-get install -y qemu-utils)
#
# CirrOS is committed to tests/data/ and does NOT need to be re-downloaded.
# The cirros_committed_* test in tests/corpus.rs reads directly from tests/data/.
set -euo pipefail

DEST="$(cd "$(dirname "$0")" && pwd)"

# Minimal sparse QCOW2 created by qemu-img (not committed — generated by CI).
qemu-img create -f qcow2 "${DEST}/sparse.qcow2" 10M
